pools.json

The address 16jnC5hVyjk4gE6BJtLqkkyfZHqXCB5PBu belongs to the wallet of polmine.pl.
https://www.walletexplorer.com/wallet/Polmine.pl

add: 16jnC5h.. -> Polmine

---

pools.json

based on https://github.com/btccom/Blockchain-Known-Pools/commit/6b58bb68e77c23dc34f264cb383eddc35424fd30

cleanup & add: Huobi addrs

---

pools.json

based on
- https://github.com/btccom/Blockchain-Known-Pools/commit/4711f8413cbe6e811712588933caf2e959fcba1a
- https://github.com/btccom/Blockchain-Known-Pools/commit/f01119b14ff65bc7d54caefb65573af58749905f

add: 4x addr -> rawpool.com

---

pools.json

https://mempool.space/de/block/000000000000000000003f8cb66fe1ecfb38754abc9c4d4a62b71de45fef8777
with coinbase tag:
`ºh 8\ MARA Pool - OFAC Compliant Block \A[çÆ¥Ý.ÜÉ`

add: MARA Pool

---

pools.json

Add new P2WPKH address for F2Pool (bc1qf274x7penhcd8hsv3jcmwa5xxzjl2a6pa9pxwm)

---

pools.json

https://github.com/btccom/Blockchain-Known-Pools/commit/18755fc2a1d357597f98c025c6ffd8e048a975de

1JvXhnHCi6XqcanvrZJ5s2Qiv4tsmm2UMy -> Binance Pool

---

pools.json

https://github.com/0xB10C/known-mining-pools/issues/48

add: 33SAB6pz.. -> Carbon Negative (unidentified)

---

pools.json

The address 17tUZLvy3X2557JGhceXRiij2TNYuhRr4r very likely belongs to Poolin.com

add: 17tUZL... -> Poolin

---

pools.json

Poolin very likely started using these addresses recently
1E8CZo2S3CqWg1VZSJNFCTbtT8hZPuQ2kB - started 13th October 2021
1GNgwA8JfG7Kc8akJ8opdNWJUihqUztfPe - started 13th October 2021
14sA8jqYQgMRQV9zUtGFvpeMEw7YDn77SK - started 1st November 2021

add: three Poolin addresses

---

pools.json

add: tag + addr ->  KuCoinPool

---

pools.json

mined, e.g., 000000000000000000011ab4bba41037644ccbc64a4e29745704a73a0b5c51d9

add: tag+addr for Terra Pool

---

pools.json

https://www.ultimuspool.com/en
mined, e.g, 000000000000000000071a6b18ff27cd3af4927d43931fac9684bcb6bd7c08f5

add: tag+addr for Ultimus Pool

---

pools.json

mined e.g. https://miningpool.observer/template-and-block/00000000000000000002e59f0a7004ccc2c11e98d2312fbc4b3ad4a7bd60f0a6

Add Pega Pool

---

entities/poolin.json
generated/pools.json

closes #64
btw, is the second link necessary?

add: new poolin addr & tag

---

entities/mara-pool.json
generated/pools.json

add: new mara pool addr

---

pools/emcdpool.json
pools/mara-pool.json

This is a squashed version of @guybrushino's #91 PR.

Add new MaraPool and EMCD coinbase tags

---

pools/secpool.json

- https://github.com/mempool/mining-pools/commit/62b15b6bc4b936164cfadda9c8a345c880c578e3
- https://mempool.space/address/3Awm3FNpmwrbvAFVThRUFqgpbVuqWisni9
closes https://github.com/bitcoin-data/mining-pools/issues/95

add: SecPool

---

pools/cleanincentive.json

This pool uses the coinbase output address bc1qrm09asqsxh2l7pjxjlltm53tx689dp2amzupzq and has recently been tagging its blocks with "Validated with Clean Energy". The first block mined was tagged with DMGBlockchain, which could indicate they are DMG or use DMG software and didn't have the correct coinbase tag configured before mining their first block.
The pool also included two zero-fee transactions, one of which is an inscription. Since these tx
normally wouldn't be relayed, the pool either mined its own tx or tx from a bussiness partner.
The first zero-fee transaction is
1a6466600e05ccf5b63ded29d4a1a067ce33b79cd1252754ead733f21fae1775
to
bc1pchpwalpdtcfp3aunxj6mjs7f0qwngsa8rwfu4vyzz3dtyh7fvlksqf2eex
which was spent by
f9aa65bb55baa3e2ba95deac89afc99d28934cdb613e72abe20b1f25a0c848ee
to …

add: CleanIncentive

---

pools/white-pool.json

add: WhitePool

---

pools/f2pool.json

F2Pool currently mines to the address 1K6KoYC69NnafWJ7YgtrpwJxBLiijWqwa6

add: new F2Pool tag and address

---

pools/spiderpool.json

The current SpiderPool might be different from the SpiderPool active between 2019 and 2021.
https://mempool.space/mining/pool/spiderpool

update: spiderpool new addr and coinbase tag

---

pools/mara-pool.json

as per https://github.com/mempool/mining-pools/pull/65

add: new mara pool tag

---

pools/bitfufu.json

see also https://github.com/mempool/mining-pools/pull/71

add: BitFuFu pool

---

pools/maxipool.json

see also https://github.com/mempool/mining-pools/pull/66

add: MaxiPool

---

pools/mining-dutch.json

See also https://github.com/mempool/mining-pools/issues/67

add: Mining-Dutch

---

pools/binance-pool.json

closes https://github.com/bitcoin-data/mining-pools/issues/108

add: new binance pool address

---

pools/antpool.json
pools/f2pool.json
pools/foundry-usa.json
pools/viabtc.json
qa/check-data.py

I noticed that many of the major pools had newer addresses. This just updates the few I came across.

Add current addresses for major pools

---

pools/luxor.json

as per https://github.com/mempool/mining-pools/pull/79/commits/14fd1f9ad0dcb83d80bc71cbd9eeef4bdcc6e0d4

add: new luxor address 32BfKjhByDSxx3BM5vUkQ3NQq9csZR6nt6
