- pools.json
This pool was active between block height 578638 and 622859. The real entity behind the pool is unknown, however all have CN/TT as coinbase tag. All coinbase outputs were created to 3QLeXx1J9Tp3TBnQyHrhVxne9KqkAS9JSR.
> add: CN/TT pool

- pools.json
BitFury only started to include the coinbase tag "/BitFury/" with block 352363 but always mined to the address 1FeDtFhARLxjKUPPkQqEBL78tisenc9znS.
> add: 1FeDtF.. -> BitFury

- pools.json
The addresses 1KTNEBhQdj81UhDkJaoe3r8VtAsrnmpmnS and 17JJ3oZyF4ShQMGukDjpMWhmooCjEvoVVB were used by MegaBigPower
> add: 1KTNEB.. -> MegaBigPower

- pools.json
1AM2fYfpY3ZeMeCKXmN66haoWxvB89pJUx belongs to the same wallet as 1ACAgPuFFidYzPMXbiKptSrwT74Dg8hq2v which belongs to DPOOL.
> add: 1AM2fYfp.. -> DPOOL

- pools.json
The address 18xf3MQvdVzKhyRvog8Q5P5THWvSjJUkzf was used by MegaBigPower.
https://oxt.me/address/18xf3MQvdVzKhyRvog8Q5P5THWvSjJUkzf
See also https://github.com/0xB10C/known-mining-pools/pull/9
> add: 18xf3MQ.. -> MegaBigPower

- pools.json
35qGBQsRQb8CSUzcSWktMykeA6zm5iCEJJ and 3DXfeMBimuvN3TWnQXDhr47P8M8yxMy9Pd belong to the same wallet.
This wallet belongs to Poolin, as visible in the coinbase transaction from the newer address 36n452uGq1x4mK7bfyZR8wgE47AnBb2pzi belonging to the same wallet. 
https://www.walletexplorer.com/wallet/009b95d4e0011c38/addresses
> add: 3DXfe.. and 35qGB.. -> Poolin

- pools.json
The address 3A2dwyVPbZc41vvmJVYxYsrkvNKnz2B4wN very likely belongs to Poolin.
See also: https://github.com/0xB10C/known-mining-pools/pull/16
> add: 3A2dwyV.. -> Poolin

- pools.json
ckpool used both the coinbase output address 3P8sR3K8wAk3bom7tqpr5VrzCz9TVYNTQd and the tag `ckpool`
> add: ckpool, 3P8sR.. -> ckpool

- pools.json
UKRPool used the address 125K2xfiBdae42gSKiCGwi85Frpy1vHmGj and the coinbase tag `Ukrpool.com`.
The same address was later used by with the tag `hash.okkong.com`. See: ff7aa4a53cef6907fb0ddc00447184df63fbcf3eb1b961ad9092e6eb6c8cae89
> add:  Ukrpool.com, 125K2xfi..-> UKRPool

- pools.json
All coinbase transactions with the output address 1Ca1KNQQo8akbrwTjjXuk8aikvC2pwodU2 contain the coinbase tag `BTCPool`.
The website for BTCPool is unknown.
> add: 1Ca1KNQ -> BTC Pool

- pools.json
based on https://github.com/btccom/Blockchain-Known-Pools/commit/599491245a65de2721df62e0ed12c6982aaffd6b
The link to https://www.arkpool.com/ seems to be dead, so not adding it here.
> /ArkPool/, 1QEiAhdH -> ArkPool

- pools.json
See https://github.com/0xB10C/known-mining-pools/issues/28
This pool probably forgot to set his coinbase tag or don't wants to be identified.
> add: BTCPool -> BTCPool (unidentified)

- pools.json
This pool mined e.g. 00000000000000000003256ad9a22dd95b6ceaeb2377068040cc101fcf14d93c
and 00000000000000000008c659de6cae2595e4de6e9fb008e5a6aa65a8cc0ecf06 recently.
The self-reported BTC hashrate on easy2mine.com of just over 1 EH/s fits in regards to blocks found per day.
> add: /E2M/ -> WAYI.CN

- pools.json
Addresses are most probably matched by whole strings. An extra space in the field will throw off some old block attribution. (f.e. mempool.space)
>  Remove superfluous space in address field

- pools.json
A bunch of Binance coinbase messages take the form of `binance/or...`, `binance/fr....`. Notably without a `/` prefix.
https://btc.com/000000000000000000021ccf3fd7e6e507633f62ffdda3640e487de9037f7e67
> Add binance/ pattern

- pools.json
Updated the website for TogetherPool and changed 1M1X to Poolin according to the [pools.json](https://github.com/blockchain/Blockchain-Known-Pools/blob/master/pools.json) list from Blockchain.com.
> add: TogetherPool and Poolin

- pools.json
Reasoning:
1. paid >388 BTC to known F2Pool address in ba1a127619f471198673e057bf20097588525dfe0bf1281009c70a1a6afb5367
2. includes zero-fee transactions (commonly done by f2pool)
3. zero-fee transactions are
a) a f2pool payout: https://oxt.me/transaction/6af178a9918940c7643a7f8c5468bbec207e8fce38674a6da34729ea96c5cb1a
b) a f2pool-owned coinbase consolidation: https://oxt.me/transaction/676bce7029a589a1525cccd01ca1c0d4387189989e8691c7ef57ab3bbfe3f090
Closes #45
> add: bc1q7wedv4zdu5... -> f2pool

- pools.json
Address 3LC8dDKyBsrWPfzhXyt7aAyjXxGYkfDdHu was used in the first
three blocks that MARA Pool mined.
The address then switched to 3D72db1KMCnj7FL7MBsmxTw81z2bVu4UN5.
Closes #35
> add: 3LC8dDKy.. & 3D72db1KM.. ->  MARA Pool

- pools.json
low hashrate pool
mined, e.g., 00000000000000000000ec7d41e70e4a1b81bbebbdb5e33a57399bd86854c1c3
> add: tag+addr for BlockFills

- generated/pools.json
- pools/tigerpool-net.json
- pools/tigerpool.json
Not adding "tigerpool.net" as link as this site isn't a mining pool.
Also adds 39pLhpmYEhYaz6MrxvBVndTEK1x45MAsdN as a Tiger Pool address.
Switch from 'tiger' to 'tiger/tigerpool.net' at some point in 07-2018:
- Last 'tiger' block: 2018-07-02 04:02 https://mempool.space/block/00000000000000000004b07bb4fe6f4dc224d78c91b52eb78826f1b04ce1fbd5
- First 'tiger/tigerpool.net' block: 2018-07-26 07:27 https://mempool.space/block/000000000000000000150389188939b867d93f03f9f6f6e293a47c625c189386
> cleanup: consolidate tigerpool

- contrib/generate-json-pool-list.py
- contrib/generate-old-pools-json.py
The files were previously located in the "generated" folder which was removed in https://github.com/bitcoin-data/mining-pools/pull/79. As the folder does not exist anymore, the scripts fail.
> fix: generate files to current directory

- pools/carbon-negative-unidentified.json
The miner switched to a new address (3KZDwmJHB6QJ13QPXHaW7SS3yTESFPZoxb) but kept re-using the same coinbase script hex of `01201209090920090920090`.
Closes #83
related #48
> add: Carbon Negative miner address

- pools/luxor.json
Adds the tag `Powered by Luxor Tech` and the address `39bitUyBcUu3y3hRTtYprKbTp712t4ZWqK` to the Luxor pool entity.
See also: https://explorer.btc.com/btc/pool/99
> add: Luxor Pool tag and address

- pools/nicehash.json
NiceHash apparently has their own pool (see #86). They've mined about 30 blocks since October 2022.
See https://www.nicehash.com/my/easymining/recent-blocks?coin=BTC&page=0 (requires login)
Some blocks they've mined:
- https://mempool.space/block/0000000000000000000191fabac23dc46064d274bb6c651275774d70c582d90e
- https://mempool.space/block/000000000000000000049348fb58bc21dbb230893b622bbb478c5fe8a6f3543e
- https://mempool.space/block/000000000000000000016df2f1587f6ef04df009240be3c7f42040f2b432f78a
> add: NiceHash address and tag

- pools/ocean.json
The pool pays to the miners directly and thus doesn't have a coinbase output address
See e.g. this block:
https://mempool.space/block/0000000000000000000247e9c51c7e3091d43dbd5f5ea30539d0307c1ad4a9cc
> add: ocean.xyz pool
